name: Depoy a Node code on EC2 using Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH into Server
        uses: appleboy/ssh-action@v0.1.6
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /home/ubuntu/my-app
            git pull origin main
            docker-compose up -d --build
